title: Welcome to Introduction to Python & Dev for Analysis
description: Build faster, automate the boring stuff, and secure your code. Master the modern Python and Git workflow designed for serious data wrangling
url: "https://stegr81.github.io"
baseurl: "/Python-and-Dev-for-Analysis"
theme: jekyll-theme-minimal
