title: Introduction to Python & Dev for Analysis
description: For anyone who analyses large amounts of data and would like a better way of doing it. Or, maybe you're just curious.
url: "https://stegr81.github.io"
baseurl: "/Python-and-Dev-for-Analysis"
theme: jekyll-theme-minimal
